### ISSUE TITLE
乱码怎么弄

### ISSUE THREAD

**Issue by luoo369** [Acamy/pet-chain-buyer#1]
璇疯緭鍏ラ獙璇佺爜锛bgnx
歍raceback (most recent call last):
  File "pet_chain.py", line 91, in purchase
    self.captcha = input('璇疯緭鍏ラ獙璇佺爜锛?)
  File "<string>", line 1, in <module>
NameError: name 'bgnx' is not defined
success================================================
success================================================
success================================================
success================================================
璇疯緭鍏ラ獙璇佺爜锛ebry
歍raceback (most recent call last):
  File "pet_chain.py", line 91, in purchase
    self.captcha = input('璇疯緭鍏ラ獙璇佺爜锛?)
  File "<string>", line 1, in <module>
NameError: name 'ebry' is not defined
success================================================
璇疯緭鍏ラ獙璇佺爜锛q7db
歍raceback (most recent call last):
  File "pet_chain.py", line 91, in purchase
    self.captcha = input('璇疯緭鍏ラ獙璇佺爜锛?)
  File "<string>", line 1, in <module>
NameError: name 'q7db' is not defined

乱码怎么弄

**Comment by luoo369** [comment]
E:\Python36\new\pet-chain-buyer-master>python pet_chain.py
Traceback (most recent call last):
  File "pet_chain.py", line 10, in <module>
    import ocr
  File "E:\Python36\new\pet-chain-buyer-master\ocr.py", line 9
SyntaxError: Non-ASCII character '\xe4' in file E:\Python36\new\pet-chain-buyer-master\ocr.py on line 9, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

E:\Python36\new\pet-chain-buyer-master>

**Comment by Acamy** [comment]
应该是cmd.exe默认中文编码是gbk的原因，而程序代码为utf-8
参考：[python 中文乱码出现，不知道是什么原因？ - 大头的回答 - 知乎](https://www.zhihu.com/question/40856143/answer/112462619)
